name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
    - title: "🚀 Features"
      labels:
          - "feat"
    - title: "🐛 Bug Fixes"
      labels:
          - "fix"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver: "patch"
