name: Publish Extension

on:
    push:
        tags:
            - "v*.*.*"
        
jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 20.x
              uses: actions/setup-node@v2
              with:
                  node-version: 20.x

            - run: npm install

            - name: Install vsce
              run: npm install -g @vscode/vsce

            - name: Install ovsx
              run: npm install -g ovsx

            - name: Package Extension
              run: vsce package --no-git-tag-version

            - name: Publish to VS Marketplace
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
              run: vsce publish --no-git-tag-version --packagePath *.vsix

            - name: Publish to Open VSX Registry
              env:
                  OVSX_PAT: ${{ secrets.OVSX_PAT }}
              run: ovsx publish *.vsix
