name: Publish Extension

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - run: npm install

    - name: Install vsce
      run: npm install -g @vscode/vsce

    - name: Publish Extension
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: vsce publish --no-git-tag-version