name: Publish Extension

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 20.x
              uses: actions/setup-node@v2
              with:
                  node-version: 20.x

            - run: npm install

            - name: Install vsce
              run: npm install -g @vscode/vsce

            - name: Publish Extension
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
              run: vsce publish --no-git-tag-version

            - name: Generate Release Notes
              id: generate_notes
              uses: release-drafter/release-drafter@v5
              with:
                  config-name: release-drafter.yml

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Stack trance analyzer ${{ github.ref }}
                  body: ${{ steps.generate_notes.outputs.notes }}
                  draft: false
                  prerelease: false
